name: MorpheusHelper

repo:
  owner: Defelo
  name: MorpheusHelper
  icon: "https://github.com/Defelo.png"

author: Defelo

languages:
  - en
default_language: en

roles:
  admin:
    name: Administrator
    check_assignable: false

  op:
    name: Operator
    check_assignable: false

  mod:
    name: Moderator
    check_assignable: false

  team:
    name: Team
    check_assignable: false

  verified:
    name: Verified
    check_assignable: true

  mute:
    name: Mute
    check_assignable: true

permission_levels:
  administrator:
    name: Administrator
    level: 3
    aliases: [admin, a]
    if:
      permissions: [administrator]
      roles: [admin]

  operator:
    name: Operator
    level: 2
    aliases: [op, o]
    if:
      roles: [op]

  moderator:
    name: Moderator
    level: 1
    aliases: [mod, m]
    if:
      roles: [mod]

default_permission_level: administrator
default_permission_overrides:
  sudo:
    clear_cache: owner
    reload: owner
    stop: owner
    kill: owner

teamler_level: moderator
