version: '3.7'
services:
  morpheushelper:
    container_name: morpheushelper
    image: defelo/morpheushelper
#    image: defelo/morpheushelper:experimental
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      TOKEN: '<TOKEN>'
      DB_HOST: 'db'
      DB_PORT: 3306
      DB_DATABASE: 'morpheushelper'
      DB_USER: 'morpheushelper'
      DB_PASSWORD: 'morpheushelper'
      SENTRY_DSN: ''
      OWNER_ID: ''

  db:
    container_name: mariadb
    image: mariadb
    # image: jsurf/rpi-mariadb
    restart: always
    environment:
      MYSQL_USER: "morpheushelper"
      MYSQL_PASSWORD: "morpheushelper"
      MYSQL_DATABASE: "morpheushelper"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      # MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - './mysql_data:/var/lib/mysql'
