version: '3.7'

x-defaults: &defaults
  env_file: morpheushelper.env
  restart: always
  networks:
    - morpheushelper

services:
  morpheushelper:
    << : *defaults
    image: defelo/morpheushelper
#    image: defelo/morpheushelper:develop
    tty: true
    depends_on:
      - db
      - redis

  db:
    << : *defaults
    image: mariadb
#    image: jsurf/rpi-mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql

  redis:
    << : *defaults
    image: redis:alpine
    volumes:
      - ./data/redis:/data

networks:
  morpheushelper:
