version: '3.7'
services:
  morpheushelper:
    container_name: morpheushelper
    image: defelo/morpheushelper
    restart: always
    tty: true
    environment:
      TOKEN: '<TOKEN>'
      DB_HOST: 'db'
      DB_PORT: 3306
      DB_DATABASE: 'morpheushelper'
      DB_USER: 'morpheushelper'
      DB_PASSWORD: 'morpheushelper'
      SENTRY_DSN: ''
