version: '3.7'

x-defaults: &defaults
  env_file: morpheushelper.env
  restart: always
  networks:
    - morpheushelper

services:
  morpheushelper:
    << : *defaults
    image: defelo/morpheushelper
#    image: defelo/morpheushelper:experimental
    tty: true
    depends_on:
      - db

  db:
    << : *defaults
    image: mariadb
#    image: jsurf/rpi-mariadb
    volumes:
      - './mysql_data:/var/lib/mysql'

networks:
  morpheushelper:
